export const AUTH_SIGN_OUT_INITIATE = 'AUTH_SIGN_OUT_INITIATE';
export const AUTH_SIGN_OUT_SUCCEED = 'AUTH_SIGN_OUT_SUCEED';
export const AUTH_SIGN_IN_INITIATE = 'AUTH_SIGN_IN_INITIATE';
export const AUTH_SIGN_IN_SUCCEED = 'AUTH_SIGN_IN_SUCEED';
export const AUTH_SIGN_UP_INITIATE = 'AUTH_SIGN_UP_INITIATE';
export const AUTH_SIGN_UP_SUCCEED = 'AUTH_SIGN_UP_SUCEED';
